#!/bin/bash
# So Golang does not support C-like macros.

[ -z "$1" ] && echo "Usage: $0 [expression]" && exit 1;

tmp=$(mktemp "./XXXXXX.go");

EXPRESSION="$1";

#cp -rv "./mandelbrot.go" "$tmp";
cat "./mandelbrot.go" | awk '{ gsub("{{EXPRESSION}}","'"$EXPRESSION"'",$0); print($0); }' > "$tmp";

go run "$tmp";

rm "$tmp";
