#!/bin/bash
# So Golang does not support C-like macros.

tmp=$(mktemp "./XXXXXX.go");

EXPRESSION="x*x + y*y < 4";
TRANSFORMX="x*x - y*y + x0";
TRANSFORMY="2*x*y + y0";

sub() {
	str="";
	for key in $@; do
		val=$(eval echo "\$$key");
		str='gsub("{{'"$key"'}}","'"$val"'",$0); '$str;
	done
	awk '{'"$str"'print($0); }';
}

#cp -rv "./mandelbrot.go" "$tmp";
cat "./mandelbrot.go" | sub "EXPRESSION" "TRANSFORMX" "TRANSFORMY" > "$tmp";

time go run "$tmp";

rm "$tmp";
