#!/bin/bash
# So Golang does not support C-like macros.

tmp=$(mktemp "./XXXXXX.go");

# Render output
RESX=1000;
RESY=1000;

# Some maths
EXPRESSION="x*x + y*y < 4";
TRANSFORMX="x*x - y*y + x0";
TRANSFORMY="2*x*y + y0";
ITERATIONS=100;

# View position in the set
#VIEWX=0.213;
#VIEWY=-0.5455;
#VIEWW=0.1;
#VIEWH=0.1;
VIEWX="0.0";
VIEWY="0.0";
VIEWW="4.0";
VIEWH="4.0";

sub() {
	str="";
	for key in $@; do
		val=$(eval echo "\$$key");
		str='gsub("{{'"$key"'}}","'"$val"'",$0); '$str;
	done
	awk '{'"$str"'print($0); }';
}

#cp -rv "./mandelbrot.go" "$tmp";
cat "./mandelbrot.go" | sub "RESX" "RESY" "VIEWX" "VIEWY" "VIEWW" "VIEWH" "ITERATIONS" "EXPRESSION" "TRANSFORMX" "TRANSFORMY" > "$tmp";

time go run "$tmp";

rm "$tmp";
